pipeline {
    agent any
    
    stages {
        stage('Clean'){
            steps{
                script{
                    sh 'docker stop $(docker ps -a -q)'
                    sh 'docker rm $(docker ps -a -q)'
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    try {
                        sh 'docker-compose build'
                    } catch(e) {
                        currentBuild.result = "FAILURE"
                    } finally {
                        
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }
}